language: python
python:
  - "2.7"
# install pip packages
install:
  - "pip install -r requirements.txt"
script:
  - nosetests
  - pylint --errors-only bookshelf --ignore=models.py,controllers.py
  - pylint --errors-only tests